---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: all-container-not-resources 
  labels:
    app: all-container-not-resources 
spec:
  # 初始容器
  initContainers:
  - name: echo
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "echo hello world"

  # 主容器
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
---
#
# 此资源所在namespace的describe关键信息如下所示
#   No resource quota.
#   
#   Resource Limits
#    Type       Resource  Min    Max    Default Request  Default Limit  Max Limit/Request Ratio
#    ----       --------  ---    ---    ---------------  -------------  -----------------------
#    Container  cpu       200m   400m   200m             200m           -
#    Container  memory    256Mi  512Mi  256Mi            256Mi          -
#
# 此资源中 所有主容器 均未定义resources，各主容器的resources如下所示
#   主容器myapp01
#     resources:
#       limits:
#         cpu: 200m
#         memory: 256Mi
#       requests:
#         cpu: 200m
#         memory: 256Mi
#   主容器busybox
#     resources:
#       limits:
#         cpu: 200m
#         memory: 256Mi
#       requests:
#         cpu: 200m
#         memory: 256Mi
#
