apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: wyc
  name: app03
spec:
  # <== 指定其缩放的目标
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app03

  # <== 指定相应的指标 
  metrics:
    - type: "Resource"
      resource: 
        name: "cpu"
        target:
          # 度量类型,untilization表示利用率,AverageValue表示平均值
          type: "Utilization"
          # 此字段只适用于同级其type字段为Utilization的时候
          # 表示当平均利用率的目标,当达到此目标会就会扩容
          averageUtilization: 80
    - type: "Resource"
      resource:
        name: "memory"
        target:
          type: "Utilization"
          averageUtilization: 90

  # <== 指定缩时的最小副本(只能是1)及最扩时的最大副本 
  minReplicas: 2
  maxReplicas: 4



  # <== 缩放行为的设置
  behavior:
    # 向下缩放时
    # 对于向下缩放时,是有稳定窗口时间的,默认为300秒.
    # 即：当在窗口时间内,性能未达到人为设置的饱合度时
    #    百分百的进行缩放至minReplicas
    scaleDown:
      # 稳定窗口时间(秒),默认为300秒
      stabilizationWindowSeconds: 300
      # 政策
      policies:
       # 百分比
       - type: Percent
         # 100表示100%
         value: 100
         # 表示在过去的多长时间内要求策略值为真,最大值 	
         periodSeconds: 15

    # 向上缩放时
    scaleUp:
      #
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 15
    selectPolicy: Max 
