
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: pod-max-cpu-mem 
spec:
  limits:
  - max:
      cpu: "600m"        # 限制单个Pod中所有容器其最大cpu量
      memory: "768Mi"    # 限制单个Pod中所有容器其最大memory量
    type: Pod
---
#
# 此资源对象创建后,其在线manifests的关键信息如下
# spec:
#   limits:
#   - max:
#       cpu: 400m
#       memory: 512Mi
#     type: Pod
#
# 此资源对象创建后,其所在namespace其describe信息如下所示:
#   No resource quota.
#
#   Resource Limits
#     Type  Resource  Min  Max    Default Request  Default Limit  Max Limit/Request Ratio
#     ----  --------  ---  ---    ---------------  -------------  -----------------------
#     Pod   cpu       -    600m   -                -              -
#     Pod   memory    -    768Mi  -                -              -
#
