
---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: defined-requests-limits-02 
  labels:
    app: defined-requests-limits-02 
spec:
  # 主容器
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    resources:
      limits: 
        cpu: "300m"
        memory: "256Mi"
      requests:
        cpu: "20m"
        memory: "256Mi"
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
    resources:
      limits:
        cpu: "100m"
        memory: "256Mi"
      requests:
        cpu: "20m"
        memory: "256Mi"
---
#
# 此Pod所在namespace其describe关键信息如下所示
#   No resource quota.
#
#   Resource Limits
#     Type  Resource  Min  Max    Default Request  Default Limit  Max Limit/Request Ratio
#     ----  --------  ---  ---    ---------------  -------------  -----------------------
#     Pod   cpu       -    600m   -                -              -
#     Pod   memory    -    768Mi  -                -              -
#
# 此Pod中 所有主容器 均定义了resources.limits。总cpu限制未超过400m，总memory限制未超过512Mi
#   此Pod是会被创建的。 
#
