
---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: exceed-total-number 
  labels:
    app: exceed-total-number 
spec:
  # 主容器
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    resources:
      limits: 
        cpu: "500m"
        memory: "600Mi"
      requests:
        cpu: "20m"
        memory: "126Mi"
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
      requests:
        cpu: "20m"
        memory: "126Mi"
---
#
# 此Pod所在namespace其describe关键信息如下所示
#   No resource quota.
#
#   Resource Limits
#     Type  Resource  Min  Max    Default Request  Default Limit  Max Limit/Request Ratio
#     ----  --------  ---  ---    ---------------  -------------  -----------------------
#     Pod   cpu       -    600m   -                -              -
#     Pod   memory    -    768Mi  -                -              -
#
# 此Pod中 所有主容器 均人为定义了resources.limits。
#   总cpu已超过600m，总memory已超过768Mi。此Pod不会被创建。
#     总cpu为：500m + 200m
#     总memory为：600Mi + 256Mi
#
#   报错信息为 
#     Error from server (Forbidden): error when creating "05.pods_exceed-total-number.yaml": pods "exceed-total-number" is forbidden: [maximum cpu usage per Pod is 600m, but limit is 700m, maximum memory usage per Pod is 768Mi, but limit is 897581056]
#
