---
apiVersion: v1
kind: PersistentVolume
metadata:
  # 其pv资源是非namespace级别的资源
  name: binbin-prod-app41-data
  labels:
    project: binbin
    env: prod
    app: app41
spec:
  # 树内插件对拉存储系统
  rbd:
    # ceph存储集群其mon组件实例的连接地址
    monitors:
    - "172.31.8.201:6789"
    - "172.31.8.202:6789"
    - "172.31.8.203:6789"

    # 相应的pool和pool的image
    pool: "rbd-binbin-project-data" 
    image: "app41-data"

    # 要格式化成任何文件系统
    fsType: ext4

    # 认证信息
    user: "binbinrbd"
    keyring: "/etc/ceph/ceph.client.binbinrbd.keyring"   # binbin项目相关worker node得存在此文件

    # 是否只读，默认为false
    readOnly: false
   
  # 卷模式，pvc来匹配时是第一顺序
  #    注意：这里使用的是Filesystem，未用Block
  #    若是Filesystem
  #      那么Pod关联至与此资源对象关联的pvc后，其里面的容器在挂载Pod中的卷时就使用volumeMounts
  #    若是Block
  #      那么Pod关联至与此资源对象关联的pvc后，其里面的容器在挂载Pod中的卷时就使用volumeDevices
  #volumeMode: Block
  volumeMode: Filesystem
  
  # 所属的storageClass, pvc来匹配时是第三顺序(第二顺序是pv的标签)
  # 静态pv也可属于某个storageClass，只不过这个storageClass并非storagesclasses资源对象
  storageClassName: "binbin-project-prod-static-pv"
  
  # 访问模式
  accessModes: 
  - ReadWriteOnce
  
  # 能力(大小)
  capacity: 
    storage: 5Gi
   
  # pv的回收策略
  persistentVolumeReclaimPolicy: Retain 
--- 
