---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: binbin
  name: app41-data
  labels:
    project: binbin
    env: prod
    app: app41
spec:
  # 准备集群级别pv的顺序为
  # volumeMode--->labels--->storageClassName--->accessModes-->capacity
  
  #volumeMode: Block
  volumeMode: Filesystem 


  selector:
    matchLabels:
      project: binbin
      env: prod
      app: app41
 
  storageClassName: "binbin-project-prod-static-pv"
  
  accessModes: 
  - ReadWriteOnce 
  
  resources: 
    limits:
      storage: 5Gi 
    requests:
      storage: 5Gi 
---

