apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lili
  name: app01
  labels:
    deploy: app01
spec:
  # <== 单副本,rbd只支持单路
  replicas: 1
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
        project: wyc
        env: prod
    spec:
      # Pod级别
      volumes:
        - name: data
          rbd:
            # 其存储系统之Ceph之monitors组件的连接地址和相应volume（subvolume）的路径
            monitors:                                                            # 根据存储管理员所提供的信息
              - "172.31.7.211:6789"
              - "172.31.7.212:6789"
              - "172.31.7.213:6789"
            pool: rbd-wyc-project-data                                           # 根据存储管理员所提供的信息
            image: app01-data                                                    # 根据存储管理员所提供的信息

            # 认证的用户和kerying(不是secret哈)
            # 需要将Ceph存储系统中的client.wycrbd用户的keyring文件拷贝至相应的worker node上(得事先与k8s管理员沟通)
            # user: "client.wycrbd"
            user: "wycrbd"                                                       # 根据存储管理员所提供的信息
            keyring: "/etc/ceph/ceph.client.wycrbd.keyring"                      # 根据k8s管理员所提供的信息,各worke node上得存在

            # 在格式化时,格式化成什么文件系统
            fsType: ext4

            # 在Pod级别加载volume后,在这一层面,指定是否只读,为false表示可读写
            readOnly: false

      # 容器级别之主容器
      containers:
        - name: app01
          image: docker.io/library/busybox:latest
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: false
          command: 
            - "/bin/sh"
          args:
            - "-c"
            - "sleep 10000000"
