apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: ports-03 
  labels:
    app: ports-03
spec:
  ## 容器级别之主容器
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    imagePullPolicy: Always
    # 我这儿是进行"人类可读、被其它资源对象所引用"
    ports:
      # Pod中各主容器其ports字段下的列表名不能重复。
      #   A:建议其name的格式为：协议-port 
      #   B:Pod中各容器是共享Network名称空间,所以会杜绝Port冲突,
      #   C:其它资源对象(例如svc资源对象)匹配到此Pod后,可以调用这儿的列表名
    - name: http-80
      # 容器中应用程序的实际端口
      containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: lili
  name: ports-03
  labels:
    svc: ports-03
spec:
  selector:
    app: ports-03
  type: NodePort
  ports:
  - name: http-80
    appProtocol: http
    port: 80  # svc其CLUSTER-IP对应的端口
    protocol: "TCP"
    targetPort: "http-80" # pods/ports-03对象中有
    
