
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: containers-max-min-cpu-mem-have-ratio 
spec:
  limits:
  - default:
      cpu: "200m"        # 最少min,最大max
      memory: "256Mi"    # 最少min,最大max
    defaultRequest:
      cpu: "200m"        # 最少min,最大max
      memory: "256Mi"    # 最少min,最大max
    max:
      cpu: "400m"
      memory: "512Mi"
    min:
      cpu: "200m"
      memory: "256Mi"
    maxLimitRequestRatio: 
      cpu: 2            # 限制cpu limits/requests 的最大比值，（default/defaultRequest）。
      memory: 2         # 限制memory limits/requests 的最大比值，（default/defaultRequest）。
    type: Container
---

