---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: all-container-not-resources 
  labels:
    app: all-container-not-resources 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
---
#
# 此资源对象创建后，其所在namespace的describe关键信息如下所示
#   No resource quota.
#
#   Resource Limits
#    Type       Resource  Min    Max    Default Request  Default Limit  Max Limit/Request Ratio
#    ----       --------  ---    ---    ---------------  -------------  -----------------------
#    Container  cpu       200m   800m   200m             800m           3
#    Container  memory    256Mi  1Gi    256Mi            1Gi            3
#
# 此Pod将不会被创建,过不了kube-apiserver的访问控制,因为超过了 最大比值 3
#    主容器myapp01: 
#      resources.limits.cpu: 800m        # Default Limit
#      resources.requests.cpu: 200m      # Default Request
#          # 
#          # 超过了最大比值 3 
#          #
#      resources.limits.memory: 1Gi      # Default Limit
#      resources.requests.memory: 256Mi  # Default Request
#          #
#          # 超过了最大比值 3
#          #
#    主容器busybox
#      同理
#
#    报错信息
#      Error from server (Forbidden): error when creating "02.pods_all-container-not-resources.yaml": pods "all-container-not-resources" is forbidden: [memory max limit to request ratio per Container is 3, but provided ratio is 4.000000, cpu max limit to request ratio per Container is 3, but provided ratio is 4.000000]
#
