---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: defined-requests-limits-01 
  labels:
    app: defined-requests-limits-01 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源请求和限制
    #     有resources.limits
    #     有resources.requests
    resources:
      limits:
        cpu: "600m"      # 最小(min),最大(max),Ratio <= 3
        memory: "768Mi"  # 最小(min),最大(max),Ratio <= 3
      requests:  # requests中相关计算资源的量不能大于limits中相关计算资源的量,这是最基本的。
        cpu: "200m"      # 最小(min),最大(max),Ratio <= 3
        memory: "256Mi"  # 最小(min),最大(max),Ratio <= 3
---
#
# 此资源所在namespace的describe关键信息如下所示
#   No resource quota.
#   
#   Resource Limits
#    Type       Resource  Min    Max    Default Request  Default Limit  Max Limit/Request Ratio
#    ----       --------  ---    ---    ---------------  -------------  -----------------------
#    Container  cpu       200m   800m   200m             800m           3
#    Container  memory    256Mi  1Gi    256Mi            1Gi            3
#
# 此资源对象中 各主容器 有人为定义resoruces，其计算资源的值不可以随便定义，受LimitRange其min、max的限制
#   主容器myapp01
#     resources:
#       limits:
#         cpu: 600m
#         memory: 768Mi
#       requests:
#         cpu: 200m
#         memory: 256Mi
#
