---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lili
  name: emptydir-memory03
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emptydir-memory03
  template:
    metadata:
      labels:
        app: emptydir-memory03
    spec:
      ## Pod级别
      volumes:
      - name: emptydir-memory03
        emptyDir:
          # 指定存储介质为Memory
          medium: "Memory"
          # 没有设置大小
          #   所有主容器均未设置resources.limits.memory 或 多主容器下只要有一个主容器未设置resources.limits.memory
          #     其大小为所在worker node其物理内存的配置大小
          #   所有主容器均有设置resources.limits.memory
          #     其大小为所有主容器resources.limits.memory之和
          #sizeLimit: 500Mi

      ## 容器级别之主容器
      containers:
      - name: busybox01
        image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
        volumeMounts:
        - name: emptydir-memory03
          mountPath: /data/emptydir-memory
          readOnly: false
        command:
        - "/bin/sh"
        args: 
        - "-c"
        - "sleep 10000000000"
        resources:
          limits:
            cpu: "100m"
            memory: "256Mi"    
      - name: busybox02
        image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
        volumeMounts:
        - name: emptydir-memory03
          mountPath: /data/emptydir-memory
          readOnly: false
        command:
        - "/bin/sh"
        args:
        - "-c"
        - "sleep 100000000"
        resources:
          limits:
            cpu: "100m"
            memory: "512Mi"
---
