apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: lili
  name: storage-resource-quota-01
spec:
  hard:
    # 所有PVC，存储资源的需求(requests)总量不能超过该值。
    persistentvolumeclaims: <string>

    # 在该命名空间中所允许(limits)的PVC总量。
    requests.storage:  <string>

    # 在所有与<storage-class-name> 相关的持久卷申领中，存储请求的总和不能超过该值。
    <storage-class-name>.storageclass.storage.k8s.io/persistentvolumeclaims: <string>

    # 在与 storage-class-name 相关的所有持久卷申领中，命名空间中可以存在的持久卷申领总数。
    <storage-class-name>.storageclass.storage.k8s.io/requests.storage:  <string>
