---
apiVersion: v1
kind: PersistentVolume
metadata:
  # 其PersistentVolume资源对象是非namespace级别的
  # 各对象的名不能冲突，所以其name的前缀为项目名。
  name: wyc-app01
  labels: 
    project: wyc
    app: app01
spec:
  # 树内卷插件之csi对接"csidriver资源对象"、连接"存储系统"并指定"存储系统中的数据卷"
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 172.31.7.203
      share: /data/wyc/app01/
    volumeHandle: wyc-app01
 
  # 卷模式(必须)
  #   默认为Filesystem，还支持Block。
  #   pvc来匹配时,第一顺序。
  volumeMode: Filesystem

  ## 所属的storageClass
  #  pvc来匹配时,第三顺序,第二顺序是此资源对象的labels
  storageClassName: "wyc-static-nfs" 

  ## 访问模式
  #  必须的，没有默认值。
  #  pvc来匹配时,第四顺序。
  accessModes:
  - ReadWriteMany

  ## 能力,即大小
  #  pvc来匹配时,第五顺序
  capacity:
    storage: 10Gi

  ## pv资源对象的回收策略
  #  回收策略：当删除与之匹配的pvc资源对象后，如何处理pv资源对象。
  #  策略根据：kubectl explain pv.spec.persistentVolumeReclaimPolicy 查看
  #  Retain(保留),默认值
  #    含义：
  #      手动回收。即需要手动删除pv资源对象。删除pv资源对象是不会影响存储系统中的数据的。
  #      若不手动回收，此pv资源对象不会再被任何pvc资源对象所绑定(即使是之前与之匹配的pvc重建)。
  #  Delete(删除)
  #    含义：
  #      删除pv资源对象。删除pv资源对象是不会影响存储系统中的数据的。
  #    注意：
  #      树内卷csi插件时，此策略是否有效，得看是否安装csi-controller之Provisioner（负责针对csi上的
  #      卷进行Provisioner和Delete操作等，类似于CSI专用的CSI Controller。）
  #  Recycle（回收）
  #    含义：
  #      简单擦除（rm -rf /thevolume/*）。
  #      这是一个较旧的处理方式，已经被废弃。在 Kubernetes 1.17 版本之后，Recycle 策略已被移除，不再支持。
  persistentVolumeReclaimPolicy: Delete
---

