apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: max-min-cpu-mem-02 
spec:
  limits:
  - type: Container
    min:
      cpu: "300m"
      memory: "156Mi"
    max:
      cpu: "700m"
      memory: "550Mi"

#### 此资源对象创建后,关键信息如下
#spec:
#  limits:
#  - default:
#      cpu: 700m        # 根据max
#      memory: 550Mi    # 根据max
#    defaultRequest: 
#      cpu: 700m        # 根据max
#      memory: 550Mi    # 根据max
#    max:
#      cpu: 700m
#      memory: 550Mi
#    min:
#      cpu: 300m
#      memory: 156Mi
#    type: Container
#
