---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: containers-env-valuefrom-secrets
spec:
  containers:
  - name: client
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    imagePullPolicy: Always
    env:
    - name: USERNAME
      valueFrom: 
        secretKeyRef:
          name: db-secret01
          key: username
          optional: false
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret01
          key: password
          optional: false
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
---
