---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: containers-envfrom-secrets 
spec:
  containers:
  - name: client
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    imagePullPolicy: Always
    envFrom:
    - secretRef:
        name: db-secret02
        optional: false
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
---
