---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jmsco 
  name: app62-data
  labels:
    project: jmsco 
    env: prod
    app: app62
    fsvolume: data
spec:
  # 准备集群级别pv的顺序为
  # volumeMode--->labels--->storageClassName--->accessModes-->capacity
  
  volumeMode: Filesystem

  selector:
    matchLabels:
      project: jmsco
      env: prod
      app: app62
      fsvolume: data
 
  storageClassName: "jmsco-project-prod-static-pv"
  
  accessModes: 
  - ReadWriteMany
  
  resources: 
    limits:
      storage: 10Gi 
    requests:
      storage: 10Gi 
---
