apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lili
  name: nodename-nodeaffinity
spec:
  selector:
    matchLabels:
      app: nodename-nodeaffinity
  replicas: 6
  template:
    metadata:
      labels:
        app: nodename-nodeaffinity
    spec:
      ## Pod级别
      # 会冲突
      nodeName: node03
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: project
                operator: In
                values:
                - wyc
 
      
      ## Container级别之主容器
      containers:
      - name: myapp01
        image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
        ports:
        - name: http-80
          containerPort: 80

