apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lili
  name: myapp01
  labels:
    deploy: myapp01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp01
  template:
    metadata:
      namespace: lili
      labels:
        app: myapp01
    spec:
      nodeSelector:
        project: wyc
      containers:
        - name: myapp01
          image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
          args:
            - "-c"
            - "echo myapp01 >/usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
          ports:
            - name: http-80
              containerPort: 80
