apiVersion: v1
kind: Service
metadata:
  namespace: lili
  name: myapp01
  labels:
    svc: myapp01
spec:
  selector:
    app: myapp01
  type: ClusterIP
  ports:
    - appProtocol: http
      name: http-80
      port: 80
      targetPort: http-80 
