---
apiVersion: v1
kind: Secret
metadata:
  namespace: lili
  name: immutable-not-exist

## 没有定义immutable字段

## 类型
type: Opaque

## 使用data字段存放键值对
data:
  # 加密命令:
  #    echo "chenliang" | base64
  # 解密命令：
  #    echo "Y2hlbmxpYW5nCg==" | base64 -d
  myname: "Y2hlbmxpYW5nCg=="
---
