---
apiVersion: v1
kind: Secret
metadata:
  namespace: lili
  name: immutable-true

## 不可变
immutable: false

## 类型
type: Opaque

## 使用data字段定义键值对
data:
  # 加密命令:
  #    echo "chenliang" | base64
  # 解密命令：
  #    echo "Y2hlbmxpYW5nCg==" | base64 -d
  myname: "Y2hlbmxpYW5nCg=="
---
