---
apiVersion: v1
kind: Secret
metadata:
  namespace: lili
  name: data-stringdata-key-conflic-based-on-stringdata 
immutable: false
type: Opaque
data:
  # base64编码：
  #    echo "chenliang" | base64
  # base64编码解码：
  #    echo "Y2hlbmxpYW5nCg==" | base64 -d
  myname: "Y2hlbmxpYW5nCg=="
stringData:
  # 其键的value明文填写即可 
  myname: "lili"
---
