---
apiVersion: v1
kind: Secret
metadata:
  namespace: lili
  name: data-stringdata-archiving-to-data
immutable: false
type: Opaque 
data:
  # base64编码：
  #    echo "chenliang" | base64
  # base64编码解码：
  #    echo "Y2hlbmxpYW5nCg==" | base64 -d
  myname: "Y2hlbmxpYW5nCg==" 
stringData:
  # 其键的value明文填写即可
  myage: "24"

# 此资源对象创建后，describe或查看在线manifests时，
#   只有data字段(包含stringData中的键值对，value自动base64编码)
#   describe此资源对象时，键值对其valeu不会呈现。
#   查看此资源对象的在线manifests，键值对其value会呈现(当然是base64编码)
---
