---
apiVersion: v1
kind: Secret
metadata:
  namespace: lili
  name: just-use-the-data-field 
immutable: false
type: Opaque
data:
  # 加密命令：
  #    echo "chenliang" | base64
  # 解密命令：
  #    echo "Y2hlbmxpYW5nCg==" | base64 -d
  myname: "Y2hlbmxpYW5nCg=="
---
