apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: env-name-env-value 
  labels:
    app: env-name-env-value
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    imagePullPolicy: Always
    # 环境变量
    env:
    - name: PROTOCOL_HTTPS
      value: "https"
    - name: HOST_NAME
      value: "www.baidu.com"
    - name: PORT_HTTPS
      value: "443"
    - name: URL_PATH  # 若是PATH就冲突了
      value: "/"
    - name: SERVER_ADDRESS
      value: "$(PROTOCOL_HTTPS)://$(HOST_NAME):$(PORT_HTTPS)$(URL_PATH)"

    # 替换image中前台运行的命令
    command:
    - "/bin/bash"
    args:
    - "-c"
    - "echo $SERVER_ADDRESS >/server_address.txt  && sleep 10000"
