apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: imagepullpolicy-assign-always 
  labels:
    app: imagepullpolicy-assign-always
spec:
  containers:
  - name: myapp01
    # 此镜像存在且公开(pull时无需认证)
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16

    # 不管image的version是什么,若人为指定imagePullPolicy,建议指定always 
    imagePullPolicy: Always
