apiVersion: v1
data:
  userID: am1zY29mcw==
  userKey: QVFCV2txVm8rUElhR3hBQW1DMFFwQWpZa3N1MHpCVFdhK2ZBZ1E9PQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: jmsco-project-ceph-fs-in-jmscofs-user-key
  namespace: jmsco
type: Opaque
