apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: never 
  labels:
    app: never 
spec:
  #### Pod级别
  # <== 拉取镜像时登录Registry的相关信息
  #     若Pod中有多个容器时，镜像处于不同的Registry且都未公开(拉取时得先登录Registry)。
  #     可以将不同的Registry的登录信息保存于不同的secrets资源对象中。
  #imagePullSecrets: 
  #- "Sccrets资源对象01"
  #- "Secrets资源对象02"

  #### 容器级别之主容器 
  containers:
  - name: myapp01
    # <== 镜像
    #     镜像可能未公开(得登录Registry)
    #         可以把登录信息保存于secrets资源对象中,并在Pod级别用imagePullSecrets指定secrets资源对象。
    #     我这里的镜像已公开(拉取时不需要登录Registry)
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.17
    # <== 镜像拉取策略,不可在线修改
    #     若镜像拉取策略为Never时,只使用本地镜像,本地若没有(不会拉取，会直接报错),
    #     当然你也可以提前拉取或事后拉取(我这都没做)。 
    imagePullPolicy: Never
