---
# 创建一个 QoS 类为 BestEffort 的 Pod
#   Pod中的各容器必须没有设置memory和CPU的请求(quesets)或限制(limits)。  
#
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: pod-qosclass-to-besteffort 
  labels:
    app: pod-qosclass-to-besteffort 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    imagePullPolicy: Always
    resources:
      requests:
        ephemeral-storage: 10Gi
      limits:
        ephemeral-storage: 10Gi
  - name: myapp02
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31 
    imagePullPolicy: Always
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
