---
#
# 没有requests,但有limits,Pod在调度时会自动将limits的作为requests,Pod调度时得满足requests
#   Pod在调度时,会将满足"所有容器中其requests”的worker
#   node选择出来再根据评分,选择评分最高的worker node作为调度节点。
# 
#   容器1：
#      没有requests
#      resources.limits.cpu 10m
#      resources.limits.memory: 10Mi 
#      resources.limits.ephemeral-storage: 512Gi
#   容器2：
#      没有requests
#      resources.limits.cpu 10m
#      resources.limits.memory: 10Mi 
#      resources.limits.ephemeral-storage: 512Gi
#
#   此Pod在调度时,cpu 20m、memory 20Mi ephemeral-storage: 1024Gi
#   我的kubernetes上没有任何worker node可以完全满足,即不满足ephemeral-storage: 1024Gi
#   所以此Pod不会被调度，会处于Pending状态。 
#

apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: no-requests-have-limits-but-limits-affected-pod-scheduler 
  labels:
    app: no-requests-have-limits-but-limits-affected-pod-scheduler 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    imagePullPolicy: Always
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 100000"
    resources:
      limits:
        cpu: "10m"
        memory: "10Mi"
        ephemeral-storage: "512Gi"
  - name: myapp02
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    imagePullPolicy: Always
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 100000"
    resources:
      limits:
        cpu: "10m"
        memory: "10Mi"
        ephemeral-storage: "512Gi"

