---
#
# Pod在调度时没有worker node满足requests中某一资源的请求量
# 容器1：requests.cpu 10m  memory: 10Mi ephemeral-storage: 512Gi
# 容器2：requests.cpu 10m  memory: 10Mi ephemeral-storage: 512Gi
# 此Pod被调度时,所选的worker node需要具备如下资源的可用
#   cpu: 20m  memory: 20M  ephemeral-storage: 1024G
# 我的kubernetes其各worker node的cpu、memory的可用量均满足,但均不满
# 足1024G的可用磁盘空间(kubelet其--root-dir所在磁盘/分区),所以此Pod
# 不会被调度,处于Pending状态。
#
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: have-requests-have-limits-but-requests-affected-pod-scheduler 
  labels:
    app: have-requests-have-limits-but-requests-affected-pod-scheduler 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    imagePullPolicy: Always
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 100000"
    resources:
      requests:
        cpu: "5m"
        memory: "5Mi"
        ephemeral-storage: "10Gi"
      limits:
        cpu: "10m"
        memory: "10Mi"
        ephemeral-storage: "512Gi"
