---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: test 
  labels:
    app: test 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    imagePullPolicy: Always
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 100000"
    resources:
      requests:
        cpu: "10m"
        memory: "10Mi"
