apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: stress-exceed-memory
  labels:
    app: stress-exceed-memory
spec:
  nodeName: node01
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/k8s-base/polinux-stress:latest 
    imagePullPolicy: Always

    # 容器启动会占用100M内存,未超过其resources.limits.memory: 200Mi
    command:
    - "stress"
    args:
    - "--vm"
    - "2"
    - "--vm-bytes"
    - "512Mi"
    - "--vm-hang"
    - "1"
