apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: emptydir-sizelimit-use-pod-memory 
  labels:
    app: emptydir-sizelimit-use-pod-memory 
spec:
  ## Pod级别
  # 定义卷，使用的是emptyDir卷插件(内置)
  volumes:
  - name: emptydir-test
    emptyDir:
      sizeLimit: "10Mi"  # 大小限制
    
  ## 容器级别之主容器
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    volumeMounts:
      - name: emptydir-test
        mountPath: /data
        readOnly: false
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 100000000"
    resources:
      requests:
        memory: "10Mi"
      limits:
        memory: "10Mi"

  - name: myapp02
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    volumeMounts:
      - name: emptydir-test
        mountPath: /data
        readOnly: false
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 100000000"
    resources:
      requests:
        memory: "10Mi"
      limits:
        memory: "10Mi"

