apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: resources-requests-limits-ok-02 
  labels:
    app: resources-requests-limits-ok-02 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源限制(limits)和请求(requests)
    #     人为显示定义resources的limits,没有requests
    #     那么reauests中的key:value会根据limits中的key: value来生成
    resources:
      limits:
        cpu: "100m"
        memory: "512Mi"
      #没有requests
      #那么reauests中的key:value会根据limits中的key: value来生成
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
    # <== 资源限制(limits)和请求(requests)
    #     人为显示定义resources的limits,没有requests
    #     那么reauests中的key:value会根据limits中的key: value来生成
    resources:
      limits:
        cpu: "100m"
        memory: "512Mi"
      #没有requests
      #那么reauests中的key:value会根据limits中的key: value来生成
