---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wyc
  name: app01
  labels:
    project: wyc
    app: app01
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec: 
      # Pod级别
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: app01
          readOnly: false

      # 容器级别之主容器
      containers:
      - name: app01
        image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
        imagePullPolicy: Always
        volumeMounts:
        - name: data-volume
          mountPath: /data/
          readOnly: false
        command:
        - "/bin/sh"
        args: 
        - "-c"
        - "sleep 10000000000"
---

