---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: lili
  name: compute-resource-quota-01
spec:
  #### 每个命名资源的所需硬限制集,支持在线更改
  hard:
    # <== namespace资源对象其相关计算资源的配额示例
    #     
    limits.cpu: "16"        # 所有非终止状态的 Pod，其 CPU 限额总量不能超过该值。 
    limits.memory: "32Gi"   # 所有非终止状态的 Pod，其 Memory 限额总量不能超过该值。
    requests.cpu: "16"      # 所有非终止状态的 Pod，其 CPU 需求总量不能超过该值。等同于 cpu: "16"
    requests.memory: "32Gi" # 所有非终止状态的 Pod，其 Memory需求总量不能超过该值。等同于 memory: "32Gi"
---
#
# 此资源对象创建后，其所属ns资源对象的describe关键信息如下所示
#  Resource Quotas
#    Name:            compute-resource-quota-01
#    Resource         Used  Hard
#    --------         ---   ---
#    limits.cpu       0     16
#    limits.memory    0     32Gi
#    requests.cpu     0     16
#    requests.memory  0     32Gi
#   
#  No LimitRange resource.
#

