apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJzd3IuY24tbm9ydGgtMS5teWh1YXdlaWNsb3VkLmNvbS9xZXB5ZCI6IHsKCQkJImF1dGgiOiAiWTI0dGJtOXlkR2d0TVVCSVVGVkJSbG80VDFKU1VsWklNbEZVV0VOSlNqbzBNVEUzTnpSa05tSTJObU5pTkRjeU9UUTFObVptWWpJd016ZzBaakl4TXpKaVpXRTVabUkyT1RFMk5EYzRNVFF3WWpBMk0yWTBZVEU1TmpRM1pEWTEiCgkJfQoJfQp9Cg==
kind: Secret
metadata:
  creationTimestamp: null
  name: myhuaweicloud.com.image.read
  namespace: lili
type: kubernetes.io/dockerconfigjson
