---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: containers-max-min-cpu-mem-not-have-ratio-2 
spec:
  limits:
  - default:           # 最少min，最大max。
      cpu: "600m"      
      memory: "768Mi"
    defaultRequest:    # 最少min，最大max。相关资源计算量不能大于 default 中的计算资源量
      cpu: "200m"     
      memory: "256Mi" 
    max:
      cpu: "600m"
      memory: "768Mi"
    min:
      cpu: "200m"
      memory: "256Mi"
    type: Container
---
#
# 此资源对象创建后，其在线manifests的关键信息如下所示
#   spec:
#     limits:
#     - default:            
#         cpu: 600m
#         memory: 768Mi
#       defaultRequest: 
#         cpu: 200m
#         memory: 256Mi
#       max:
#         cpu: 600m
#         memory: 768Mi
#       min:
#         cpu: 200m
#         memory: 256Mi
#       type: Container
#
# 此资源对象创建后，其所在namespace的describe关键信息如下所示
#   No resource quota.
#   
#   Resource Limits
#     Type       Resource  Min    Max    Default Request  Default Limit  Max Limit/Request Ratio
#     ----       --------  ---    ---    ---------------  -------------  -----------------------
#     Container  cpu       200m   600m   200m             600m           -
#     Container  memory    256Mi  768Mi  256Mi            768Mi          -
#
