---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: volume-downwardapi-resourcefieldref
  labels:
    project: lili
    env: prod
    app: volume-downwardapi-resourcefieldref
  annotations:
    author: chenliang
    email: 158317096@qq.com
spec:
  # Pod级别
  volumes:
  - name: busybox-container-resources
    downwardAPI:
      items:
      - path: limits-cpu
        resourceFieldRef:
          containerName: busybox
          resource: limits.cpu
          divisor: 1m
      - path: limits-memory
        resourceFieldRef:
          containerName: busybox
          resource: limits.memory
          divisor: 1Mi 
      - path: requests-cpu
        resourceFieldRef:
          containerName: busybox
          resource: requests.cpu
          divisor: 1m
      - path: requests-memory
        resourceFieldRef:
          containerName: busybox
          resource: requests.memory
          divisor: 1Mi
  
  # 容器级别之主容器
  containers:
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    volumeMounts:
    - name: busybox-container-resources
      mountPath: /data/busybox-container-resources/
      readOnly: true
    command:
    - "/bin/sh"
    args: 
    - "-c"
    - "sleep 10000000000"
    resources:
      limits:
        cpu: "100m"
        memory: "256Mi"
---  
