
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: default-cpu-mem 
spec:
  limits:
    # <== 各Pod其container的resources.limits默认配置
    #     可在线更改
  - default:
      cpu: "500m" 
      memory: "612Mi"
    # <== 各Pod其container的resources.requests默认配置
    #     可在线更改
    defaultRequest:
      cpu: "300m"
      memory: "356Mi"
    # <== 此资源对象所在namespace下各Pod中的container
    type: Container
---
#
# 此资源对象创建后，其在线manifests的关键信息如下所示
#  spec:
#    limits:
#    - default:
#        cpu: 500m
#        memory: 612Mi
#      defaultRequest:
#        cpu: 300m
#        memory: 356Mi
#      type: Container
#
# 此资源对象所在namespace其describe的关键信息如下所示
#   No resource quota.
#   
#   Resource Limits
#    Type       Resource  Min  Max  Default Request  Default Limit  Max Limit/Request Ratio
#    ----       --------  ---  ---  ---------------  -------------  -----------------------
#    Container  cpu       -    -    300m             500m           -
#    Container  memory    -    -    356Mi            612Mi          -
#
