---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: livenessprobe-failure
  labels:
    app: livenessprobe-failure
spec:
  #### Pod级别
  # <== Pod中容器的重启策略
  #     默认值：Always
  #     可设值：Always、OnFailure、Never
  restartPolicy: Always

  #### 容器级别之主容器
  containers:
  - name: demoapp
    image: swr.cn-north-1.myhuaweicloud.com/qepyd/demoapp:v1.1
    imagePullPolicy: Always

    # <== 启动应用和命令(得60秒后才执行启动命令)
    command:
    - '/bin/sh'
    args:
    - '-c'
    - 'sleep 60; python3 /usr/local/bin/demo.py'

    # <== 端口列表(人类可读)
    ports:
    - name: http-80
      containerPort: 80

    # <== 存活探测
    livenessProbe:
      # <-- 初始探测时等待时长(单位秒)
      #     考滤到了应用的启动耗时
      initialDelaySeconds: 60
      # <-- 探测超时的秒数(默认1秒)
      timeoutSeconds: 1
      # <-- 失败次数
      failureThreshold: 3
      # <-- 成功次数
      successThreshold: 1
      # <-- 执行探测的频率(以秒为单位),默认10，最低取值为1。
      periodSeconds: 10
      # <-- 探针(问题就在这里，我故意写错，把OK写成了OOK)
      exec:
        command: 
        - '/bin/sh'
        - '-c'
        - '[ $(curl -s 127.0.0.1:80/livez) == "OOK" ]'
---
apiVersion: v1
kind: Service
metadata:
  namespace: lili
  name: livenessprobe-failure
  labels:
    app: livenessprobe-failure
spec:
  selector:
    app: livenessprobe-failure
  type: ClusterIP
  ports:
  - name: http-80
    appProtocol: http
    port: 80
    protocol: "TCP"
    targetPort: http-80
---

