---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: readinessprobe-livenessprobe
  labels:
    app: readinessprobe-livenessprobe
spec:
  #### Pod级别
  # <== Pod中容器的重启策略
  #     默认值：Always
  #     可设值：Always、OnFailure、Never
  restartPolicy: Always

  #### 容器级别之主容器
  containers:
  - name: demoapp
    image: swr.cn-north-1.myhuaweicloud.com/qepyd/demoapp:v1.1
    imagePullPolicy: Always

    # <== 启动应用和命令(得60秒后才执行启动命令)
    command:
    - '/bin/sh'
    args:
    - '-c'
    - 'sleep 60; python3 /usr/local/bin/demo.py'

    # <== 端口列表(人类可读)
    ports:
    - name: http-80
      containerPort: 80

    # <== 就绪探测，周期性，在startupProbe之后
    readinessProbe:
      # <-- 因不存在startupProbe,得考滤应用启动的时长
      initialDelaySeconds: 80
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
      periodSeconds: 10
      httpGet:
        scheme: "HTTP"
        port: 80
        path: "/readyz" 

    # <== 存活探测，周期性，在startupProbe之后
    livenessProbe:
      # <-- 因不存在startupProbe,得考滤应用启动的时长
      initialDelaySeconds: 80
      timeoutSeconds: 1
      failureThreshold: 3
      successThreshold: 1
      periodSeconds: 10
      httpGet:
        scheme: "HTTP"
        port: 80
        path: "/livez" 
---
apiVersion: v1
kind: Service
metadata:
  namespace: lili
  name: readinessprobe-livenessprobe
  labels:
    app: readinessprobe-livenessprobe
spec:
  selector:
    app: readinessprobe-livenessprobe
  type: ClusterIP
  ports:
  - name: http-80
    appProtocol: http
    port: 80
    protocol: "TCP"
    targetPort: http-80
---

