---
# 应用程序立即就能够启动成功。
# 配置有startupProbe
#    初始探测等待10秒
#    探测超时时长1秒
#    失败次数3
#    成功次数1
#    探测步骤每隔10秒
# startupProbe探测失败(我故意把探测的结果比对写错了)
#    容器会被kill掉,然后重启。
# 
---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: startupprobe-failure01
  labels:
    app: startupprobe-failure01
spec:
  #### Pod级别
  # <== 重启策略
  #     默认值：Always
  #     可设值：Always、OnFailure、Never
  restartPolicy: Always

  #### 容器级别之主容器
  containers:
  - name: demoapp
    image: swr.cn-north-1.myhuaweicloud.com/qepyd/demoapp:v1.1
    imagePullPolicy: Always

    # <== 启动应用和命令
    command:
    - '/bin/sh'
    args:
    - '-c'
    - 'python3 /usr/local/bin/demo.py'

    # <== 端口列表(人类可读)
    ports:
    - name: http-80
      containerPort: 80

    # <== 启动控制
    startupProbe:
      # <-- 实始探测时前等待时长(单位秒)，
      initialDelaySeconds: 10
      # <-- 探测超时的秒数(默认1秒)
      timeoutSeconds: 1
      # <-- 失败次数
      failureThreshold: 3
      # <-- 成功次数
      successThreshold: 1
      # <-- 执行探测的频率(以秒为单位),默认10，最低取值为1。
      periodSeconds: 10
      # <-- 探针(我故意写错了,应该是OK)
      exec:
        command: 
        - '/bin/sh'
        - '-c'
        - '[ $(curl -s 127.0.0.1/readyz) == "OOK" ]'
---
apiVersion: v1
kind: Service
metadata:
  namespace: lili
  name: startupprobe-failure01
  labels:
    app: startupprobe-failure01
spec:
  selector:
    app: startupprobe-failure01
  type: ClusterIP
  ports:
  - name: http-80
    appProtocol: http
    port: 80
    protocol: "TCP"
    targetPort: http-80 
