---
# 启动应用程序需要120秒。
# 配置有startupProbe
#    初始探测等待10秒
#    探测超时时长1秒
#    失败次数3
#    成功次数1
#    探测步骤每隔10秒
# startupProbe探测失败(应用都还没有启动)
#    重启。
#    再次达到失败次数，重启(等待10秒)
#    再次达到失败次数，重启(等待20秒)
#    ...............................
#    再次达到失败次数，重启(等待300秒)
#    注意：探测成功
---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: startupprobe-failure02
  labels:
    app: startupprobe-failure02
spec:
  #### Pod级别
  # <== 重启策略
  #     默认值：Always
  #     可设值：Always、OnFailure、Never
  restartPolicy: Always

  #### 容器级别之主容器
  containers:
  - name: demoapp
    image: swr.cn-north-1.myhuaweicloud.com/qepyd/demoapp:v1.1
    imagePullPolicy: Always

    # <== 启动应用和命令(等待120秒后再启动)
    command:
    - '/bin/sh'
    args:
    - '-c'
    - 'sleep 120; python3 /usr/local/bin/demo.py'

    # <== 端口列表(人类可读)
    ports:
    - name: http-80
      containerPort: 80

    # <== 启动控制
    startupProbe:
      # <-- 实始探测时前等待时长(单位秒)，
      initialDelaySeconds: 10
      # <-- 探测超时的秒数(默认1秒)
      timeoutSeconds: 1
      # <-- 失败次数
      failureThreshold: 3
      # <-- 成功次数
      successThreshold: 1
      # <-- 执行探测的频率(以秒为单位),默认10，最低取值为1。
      periodSeconds: 10
      # <-- 探针
      exec:
        command: 
        - '/bin/sh'
        - '-c'
        - '[ $(curl -s 127.0.0.1/readyz) == "OK" ]'
