---
apiVersion: apps/v1
kind: DaemonSet 
metadata:
  namespace: default 
  name: server 
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
        imagePullPolicy: IfNotPresent
        name: myapp
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: server
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: "TCP"
    targetPort: 80
    
