
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: containers-max-min-cpu-mem-have-ratio 
spec:
  limits:
  - default:           # 有人为指定，最少min，最大max。
      cpu: "200m"      
      memory: "256Mi"
    defaultRequest:    # 有人为指定，最少min，最大max。相关资源计算量不能大于 default 中的计算资源量
      cpu: "200m"     
      memory: "256Mi" 
    max:
      cpu: "600m"
      memory: "768Mi"
    min:
      cpu: "200m"
      memory: "256Mi"
    maxLimitRequestRatio: 
      cpu: 3            # 限制cpu limits/requests 的最大比值，（default/defaultRequest）。
      memory: 3         # 限制memory limits/requests 的最大比值，（default/defaultRequest）。
    type: Container
---

