
---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: defined-requests-limits-01 
  labels:
    app: defined-requests-limits-01 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源请求和限制
    #     有resources.requests
    #     有resources.limits
    resources:
      requests:
        cpu: "200m"      # 最小(min),最大(max)
        memory: "256Mi"  # 最小(min),最大(max)
      limits:
        cpu: "400m"      # 最小(min),最大(max)
        memory: "512Mi"  # 最小(min),最大(max)
---

