apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: myapp01-taint-noexcute-effect-comprehend
spec:
  #### Pod级别

  # 没有容忍任何的污点
  # 没有使用"指派节点"的任何方法

  #### 容器级别之主容器
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    ports:
    - name: http-80
      containerPort: 80
