apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: mem-limit-range
spec:
  limits:
  - defaultRequest:
      memory: 256Mi
    default:
      memory: 512Mi
    type: Container

#### 说明
# 对所在名称空间(lili)中的各容器设置默认memory的requests和limits
# 
