apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: cpu-limit-range
spec:
  limits:
  - type: Container
    # 支持在线更改
    defaultRequest:
      # 其0.4等于400m
      cpu: 0.4
    # 支持在线更改
    default:
      # 其0.8等于800m
      cpu: 0.8 
