apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: container-resources-requests-limits-cpu-mem-exceed-max-range 
  labels:
    app: container-resources-requests-limits-cpu-mem-exceed-max-range
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源请求(requests)和限制(limits)
    #     省略了resources.requests字段，会根据resources.limits字段中key: value进行填充
    resources:
      limits:
        # 其1000m等于1
        cpu: "1000m"
        memory: "712Mi"

## 此资源对象所在namespace中存在的几个limitrange资源对象
#  limitrange/cpu-limit-range
#    defaultrequests: 
#        cpu: 400m
#    default:
#        cpu: 800m
#    
#  limitrange/cpu-limitrange
#    defaultrequests: 
#        cpu: 500m
#    default:
#        cpu: 900m
#
#  limitrange/mem-limit-range
#    defaultrequests: 
#        memory: 256Mi
#    default:
#        memory: 512Mi
#
#  limitrange/mem-limitrange
#    defaultrequests: 
#        memory: 356Mi
#    default:
#        memory: 612Mi
#
## 此资源对象中容器其自定义的requests、limits下的cpu、memory超过了最大范围，是可以被kube-apiserver所接受的，
#  因为完全自定义的最大，不受所属Pod所在namespace中的各LimitRange的限制。
#  myapp01
#   resouces:
#     requests:
#       cpu: 1000m
#       memory: 712Mi
#     limtis:  
#       cpu: 1000m
#       memory: 712Mi
# 
