apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: container-resources-requests-cpu-mem-exceed-max-range 
  labels:
    app: container-resources-requests-cpu-mem-exceed-max-range
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源请求(requests)和限制(limits)
    resources:
      requests:
        # 其1000m等于1
        cpu: "1000m"
        memory: "712Mi"

## 此资源对象所在namespace中存在的几个limitrange资源对象
#  limitrange/cpu-limit-range
#    defaultrequests: 
#        cpu: 400m
#    default:
#        cpu: 800m
#    
#  limitrange/cpu-limitrange
#    defaultrequests: 
#        cpu: 500m
#    default:
#        cpu: 900m
#
#  limitrange/mem-limit-range
#    defaultrequests: 
#        memory: 256Mi
#    default:
#        memory: 512Mi
#
#  limitrange/mem-limitrange
#    defaultrequests: 
#        memory: 356Mi
#    default:
#        memory: 612Mi
#
## 此资源对象中其myapp01容器其自定义的requests下的cpu、memory超过了最大范围，
#  会直接报错，Pod不被kube-apiserver所接受的，
#  The Pod "container-resources-requests-cpu-mem-exceed-max-range" is invalid: 
#  * spec.containers[0].resources.requests: Invalid value: "1": must be less than or equal to cpu limit
#  * spec.containers[0].resources.requests: Invalid value: "712Mi": must be less than or equal to memory limit
# 
