apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: cpu-memory-comprehensive 
  labels:
    app: cpu-memory-comprehensive 
spec:
  containers:
  - name: busybox01
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
    # <== 资源请求和限制
    #     没有定义，则会使用最小范围(各LimitRange)相应的值

  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源请求和限制
    #     没有resources.requests，但有resources.limits，其resources.requests会根据
    #     resources.limits中的key: value对来进行填充。从而是显示指定了resources.requests和
    #     resources.limits。所以，cpu可以超过最大范围(各LimitRange)的limit。memory可以超过最小/大范围(各limitRange)的limit
    resources:
      limits:
        # cpu可以超过最大范围(各LimitRange)的limit
        # 其1000m等于1
        cpu: "1000m"
        # memory可以超过最小/大范围(各limitRange)的limit
        memory: "521Mi"
        #memory: "712Mi"

  - name: youapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
    # <== 资源请求和限制
    #     有resources.requests，但没有resources.limits，其resources.limits不会根据
    #     resources.requests中的key: value对来进行填充。从而是未显示指定了resources.requests和
    #     resources.limits。所以，cpu不能超过最大范围(各LimitRange)的limit值，memory不能超过最小范围(各limitRange)的limit
    resources:
      requests:
        # 不能超过最大范围(各LimitRange)的limit
        cpu: "900m"
        # 不能超过最小范围(各LimitRange)的limit
        memory: "512Mi"

## 此资源对象所在namespace中存在的几个limitrange资源对象
#  limitrange/cpu-limit-range
#    defaultrequests: 
#        cpu: 400m
#    default:
#        cpu: 800m
#    
#  limitrange/cpu-limitrange
#    defaultrequests: 
#        cpu: 500m
#    default:
#        cpu: 900m
#
#  limitrange/mem-limit-range
#    defaultrequests: 
#        memory: 256Mi
#    default:
#        memory: 512Mi
#
#  limitrange/mem-limitrange
#    defaultrequests: 
#        memory: 356Mi
#    default:
#        memory: 612Mi
#
## 此资源对象创建后，Pod中各容器的resources如下所示
#  busybox01
#   resouces:
#     requests:
#       cpu: 400m
#       memory: 256Mi
#     limtis:  
#       cpu: 800m
#       memory: 512Mi
#
#  myapp01
#   resouces:
#     requests:
#       cpu: 1000m
#       memory: 521Mi
#     limtis:  
#       cpu: 1000m
#       memory: 521Mi
#
#  youapp01
#   resouces:
#     requests:
#       cpu: 900m
#       memory: 512Mi
#     limtis:  # 根据最小范围(LimitRange)的limit生成
#       cpu: 900m
#       memory: 512Mi
# 
