
replicaCount: 2

image:
  containres:
    applicationContainer:
       repository: swr.cn-north-1.myhuaweicloud.com/library
       image: nginx
       tag: 1.16
       pullPolicy: IfNotPresent
    sidecarContainer01:
       repository: swr.cn-north-1.myhuaweicloud.com/chenliang
       image: admin-box
       tag: v1.2
       pullPolicy: IfNotPresent

podLabels:
  env: prod 
  app: myapp01

service:
  type: ClusterIP
  protocol: TCP
  port: 80
