apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: matchexpressions-matchfields
spec:
  ## Pod级别
  
  # 亲和
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        # 多条件
        - matchExpressions:
          - key: project
            operator: In
            values:
            - wyc
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - node03

  ## Container级别之主容器
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    ports:
    - name: http-80
      containerPort: 80
