---
apiVersion: v1
kind: PersistentVolume
metadata:
  # 其pv资源是非namespace级别的资源
  name: binbin-prod-app32-data
  labels:
    project: binbin
    env: prod
    app: app32
spec:
  # 树内插件对拉存储系统
  cephfs:
    monitors:                                                             # 根据存储管理员所提供
    - "172.31.8.201:6789"
    - "172.31.8.202:6789"
    - "172.31.8.203:6789"
    path: "/volumes/app32/data/ae1afebb-7f83-4809-9109-47a1bf1c5e52"      # 根据存储管理员所提供
    user: "binbinfs"                                                      # 根据存储管理员所提供
    secretRef: 
      name: "binbin-project-cephfs-in-binbinfs-user-key"        # 所引用的secrets资源对象,此资源对象所在namespace中得存在
    readOnly: false
   
  # 卷模式，pvc来匹配时是第一顺序
  volumeMode: Filesystem

  # 所属的storageClass, pvc来匹配时是第三顺序(第二顺序是pv的标签)
  # 静态pv也可属于某个storageClass，只不过这个storageClass并非storagesclasses资源对象
  storageClassName: "binbin-project-prod-static-pv"

  # 访问模式
  accessModes: 
  - ReadWriteMany

  # 能力(大小)
  capacity: 
    storage: 10Gi
 
  # pv的回收策略
  persistentVolumeReclaimPolicy: Delete
--- 
