---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: all-container-not-resources 
  labels:
    app: all-container-not-resources 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"

#### 说明
#  01：Pod中各容器没有resources的定义。
#  02：Pod所在namespace中有多个LimitRange资源对象,其
#      关键信息只有spec.limits.default和spec.limits.defaultRequests
#  03：Pod中各容器的resources最终是一样的。
#  04：至于所选择的是哪一个LimitRange资源对象,这个是不确定的。
#
---
