apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: cpu-limitrange
spec:
  limits:
  - type: Container
    # 支持在线更改
    defaultRequest:
      # 其0.5等于500m
      cpu: 0.5
    # 支持在线更改
    default:
      # 其0.9等于900m
      cpu: 0.9 
