apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: all-container-not-cpu-mem-requests-limits 
  labels:
    app: all-container-not-cpu-mem-requests-limits 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"

## 此资源对象所在namespace中存在的几个limitrange资源对象
#  limitrange/cpu-limit-range
#    defaultrequests: 
#        cpu: 400m
#    default:
#        cpu: 800m
#    
#  limitrange/cpu-limitrange
#    defaultrequests: 
#        cpu: 500m
#    default:
#        cpu: 900m
#
#  limitrange/mem-limit-range
#    defaultrequests: 
#        memory: 256Mi
#    default:
#        memory: 512Mi
#
#  limitrange/mem-limitrange
#    defaultrequests: 
#        memory: 356Mi
#    default:
#        memory: 612Mi
#
# 此资源对象创建后，其各容器的resources下requests、limits中的cpu、memory的来自最小范围的。
# myapp01
#   resouces:
#     requests:
#       cpu: 400m
#       memory: 256Mi
#     limtis:  
#       cpu: 800m
#       memory: 512Mi
#
# busybox
#   resouces:
#     requests:
#       cpu: 400m
#       memory: 256Mi
#     limtis:  
#       cpu: 800m
#       memory: 512Mi
#
