apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: container-resources-requests-limits-cpu-mem-exceed-max-range 
  labels:
    app: container-resources-requests-limits-cpu-mem-exceed-max-range
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源请求和限制
    #     没有resources.requests，但有resources.limits，其resources.requests会根据
    #     resources.limits中的key: value对来进行填充。从而是显示指定了resources.requests和
    #     resources.limits。所以，cpu可以超过最大范围(各LimitRange)的limit。memory可以超过最小/大范围(各limitRange)的limit
    resources:
      limits:
        # cpu可以超过最大范围(各LimitRange)的limit
        # 其1000m等于1
        cpu: "1000m"
        # memory可以超过最小/大范围(各limitRange)的limit
        memory: "521Mi"
        #memory: "712Mi"

## 此资源对象所在namespace中存在的几个limitrange资源对象
#  limitrange/cpu-limit-range
#    defaultrequests: 
#        cpu: 400m
#    default:
#        cpu: 800m
#    
#  limitrange/cpu-limitrange
#    defaultrequests: 
#        cpu: 500m
#    default:
#        cpu: 900m
#
#  limitrange/mem-limit-range
#    defaultrequests: 
#        memory: 256Mi
#    default:
#        memory: 512Mi
#
#  limitrange/mem-limitrange
#    defaultrequests: 
#        memory: 356Mi
#    default:
#        memory: 612Mi
#
## 此资源对象中容器其自定义的requests、limits下的cpu、memory超过了最大范围，是可以被kube-apiserver所接受的，
#  因为完全自定义的最大，不受所属Pod所在namespace中的各LimitRange的限制。
#  myapp01
#   resouces:
#     requests:
#       cpu: 1000m
#       memory: 521Mi
#     limtis:  
#       cpu: 1000m
#       memory: 521Mi
# 
