apiVersion: v1
data:
  key: QVFDOWVLSm1wblAzQ0JBQXZHcU9ySVFQVjd2d3NYSVdFOWpiZXc9PQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: lili-project-cephfs-in-lilifs-user-key
  namespace: lili
type: Opaque
