---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lili
  name: myapp02
  labels:
    app: myapp02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp02
  template:
    metadata:
      labels:
        app: myapp02
    spec:
      containers:
      - name: myapp02
        image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
---
