apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: pod-qosclass-to-guaranteed 
  labels:
    app: pod-qosclass-to-guaranteed
spec:
  nodeName: node01
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    imagePullPolicy: Always
    resources:
      requests:
        cpu:    "200m"
        memory: "200Mi"
      limits:
        cpu:    "200m"
        memory: "200Mi"
  - name: myapp02
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31 
    imagePullPolicy: Always
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
    resources:
      requests:
        cpu: "10m"
        memory: "10Mi"
      limits:
        cpu: "10m"
        memory: "10Mi"

      # Pod中所有主容器有做资源限制(requests和limits均得存在)
      # requests和limits下的相关限制还得满足以下要求(and)
      #   A:requests和limits下均得包含对cpu、memory的限制。
      #   B:requests和limits下其cpu、memory的值均得相同。
