apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: nginx-not-daemon
  labels:
    app: nginx-not-daemon
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    imagePullPolicy: Always
    #
    # 其image运行成容器时的命令是由CMD指令指定
    # 其为CMD ["nginx", "-g", "daemon off;"]
    # 其指令会让nginx以守护进程运行。
    # 
    # 以下使用command和args对其进行"覆盖"
    #   跟原有的不一样
    #   会影响其nginx启动
    #
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000"
