apiVersion: v1
kind: ConfigMap
metadata:
  namespace: <string>
  name: <string>
  labels: <map[string]string>
  annotations: <map[string]string>

## 提供定义键值（key value）对的字段
#  均不是必须的
#  可同时存在
#    data字段中的key不能与binaryData中的key冲突。
#    若冲突，不允许此资源对象的创建，直接报错。
#  binaryData中各key的value得base64加密后填写
#    若value是明文，不允许此资源对象的创建，直接报错。
#    当key被引用后，其value会被自动解密。
#    若base64加密后，其只会是单行数据。
#  data中各key的value不需要任何的加密
#    当key被引用后，其value没有自动解密一说
#    value可以是单行或多行。
#    当value为多行时，"|"后换行填写，例如
#      key: |
#        数据
#        数据
#  只用data字段即可
#    因为configmaps资源对象用于将非机密性的数据保存到键值对（key value）中
binaryData: <map[string]string>
data: <map[string]string>

### 不可变的(根据其值决定不可变是否)
#  没有默认值
#    不指定此字段，此资源对象在线manifests没有此字段，
#    此资源对象是可变的，那么此字段也是可变的。
#  若值为false
#    此资源对象在线manifests拥有此字段，
#    此资源对象是可变的，那么此字段也是可变的。
#  若值为true
#    此资源对象在线manifests拥有此字段，
#    此资源对象是不可变的，那么此字段也是不可变的。
immutable: <boolean>
