---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: lili
  name: projected-configmap
immutable: false
data:
  file01.txt: |
    1111
    1111
  file02.txt: |
    2222
    2222
---


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lili
  name: projected-configmap
  labels:
    project: lili
    env: prod
    app: projected-configmap
spec:
  replicas: 2
  selector:
    matchLabels:
      project: lili
      env: prod
      app: projected-configmap
  template:
    metadata:
      labels:
        project: lili
        env: prod
        app: projected-configmap
    spec:
      # Pod级别
      volumes:
      - name: config
        projected:
          sources: 
          - configMap:
              name: projected-configmap 
              optional: false              
       
      # 容器级别之主容器
      containers:
      - name: busybox
        image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
        volumeMounts:
        - name: config 
          mountPath: /data/config/
          readOnly: true
        command:
        - "/bin/sh"
        args: 
        - "-c"
        - "sleep 10000000000"
        resources:
          limits:
            cpu: "100m"
            memory: "256Mi"
---

