---
apiVersion: v1
kind: Secret
metadata:
  namespace: lili
  name: projected-secret 
immutable: false
type: Opaque
data:
  # 加密命令：
  #    echo "chenliang" | base64
  # 解密命令：
  #    echo "Y2hlbmxpYW5nCg==" | base64 -d
  myname: "Y2hlbmxpYW5nCg=="
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lili
  name: projected-secret
  labels:
    project: lili
    env: prod
    app: projected-secret
spec:
  replicas: 2
  selector:
    matchLabels:
      project: lili
      env: prod
      app: projected-secret
  template:
    metadata:
      labels:
        project: lili
        env: prod
        app: projected-secret
    spec:
      # Pod级别
      volumes:
      - name: secret
        projected:
          sources: 
          - secret:
              name: projected-secret
              optional: false   
       
      # 容器级别之主容器
      containers:
      - name: busybox
        image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
        volumeMounts:
        - name: secret 
          mountPath: /data/secret/
          readOnly: true
        command:
        - "/bin/sh"
        args: 
        - "-c"
        - "sleep 10000000000"
        resources:
          limits:
            cpu: "100m"
            memory: "256Mi"
---

