---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: livenessprobe-is-periodic 
  labels:
    app: livenessprobe-is-periodic 
spec:
  #### Pod级别
  # <== Pod中容器的重启策略
  #     默认值：Always
  #     可设值：Always、OnFailure、Never
  restartPolicy: Always

  #### 容器级别之主容器
  containers:
  - name: demoapp
    image: swr.cn-north-1.myhuaweicloud.com/qepyd/demoapp:v1.1
    imagePullPolicy: Always

    # <== 启动应用和命令(120秒后才会启动,启动耗时大概140秒)
    command:
    - '/bin/sh'
    args:
    - '-c'
    - 'sleep 120; python3 /usr/local/bin/demo.py'

    # <== 端口列表(人类可读)
    ports:
    - name: http-80
      containerPort: 80

    # <== 存活探测，周期性的，探测失败会导致容器重启(和启动探测startupProbe一样)
    #     若容器未定义启动探测(startupProbe),其初始探测的等待时长要把应用程序的启动
    #     时长考滤进来。
    livenessProbe:
      # <-- 探测前的等待时长
      initialDelaySeconds: 10
      # <-- 探测超时的秒数(默认1秒)
      timeoutSeconds: 1
      # <-- 失败次数
      failureThreshold: 3
      # <-- 成功次数
      successThreshold: 1
      # <-- 执行探测的频率(以秒为单位),默认10，最低取值为1。
      periodSeconds: 10
      # <-- 探针
      exec:
        command: 
        - '/bin/sh'
        - '-c'
        - '[ $(curl -s 127.0.0.1:80/livez) == "OK" ]'
      # <-- 探针(我写对了的)
      #httpGet:
      #  scheme: "HTTP" 
      #  port: 80
      #  path: "/livez" 
---
apiVersion: v1
kind: Service
metadata:
  namespace: lili
  name: livenessprobe-is-periodic 
  labels:
    app: livenessprobe-is-periodic 
spec:
  selector:
    app: livenessprobe-is-periodic 
  type: ClusterIP
  ports:
  - name: http-80
    appProtocol: http
    port: 80
    protocol: "TCP"
    targetPort: http-80
---

