apiVersion: v1
kind: Secret
metadata:
  namespace: <string>
  name: <string>
  labels: <map[string]string>
  annotations: <map[string]string>

####### 不可变
#  默认值为nil
#    此资源对象没有此字段,此资源对象是可变的。
#  值为false
#    此资源对象拥有此字段,此资源对象是可变的。
#  值为true
#    此资源对象拥有此字段,此资源对象是不可变的。
immutable: <boolean>

####### 类型
#  https://kubernetes.io/zh-cn/docs/concepts/configuration/secret/#secret-types
#  默认值：Opaque
#  可设值：kubernetes.io/service-account-token  
#          kubernetes.io/dockercfg
#          kubernetes.io/dockerconfigjson
#          kubernetes.io/basic-auth
#          kubernetes.io/ssh-auth
#          kubernetes.io/tls
#          bootstrap.kubernetes.io/token
type: <string>

####### 存放键值对的字段，常用data字段。
# 此字段中的键其value得base64加密后填写(不然拒绝此资源对象创建)。
data: <map[string]string>

# 此字段中的键其value不需要base64加密后填写。
stringData: <map[string]string>

# 在describe此资源对象时，不会存在stringData字段。会存在data字段。
# 查看此资源对象的在线manifests时，不会存在stringData字段，会存在data字段。
# 若创建此资源对象时，stringData字段中有键值对，会将其放在data字段中(value也会被自动base64加密)
# data、stringData中的键冲突，以stringData中的为准。
