apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: stress-memory-bu-not-exceed-limit
  labels:
    app: stress-memory-bu-not-exceed-limit 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/k8s-base/polinux-stress:latest 
    imagePullPolicy: Always
    # 对memory的使用进行限制
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "200Mi"
    # 容器启动会占用100M内存,未超过其resources.limits.memory: 200Mi
    command:
    - "stress"
    args:
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "100M"
    - "--vm-hang"
    - "1"
