apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: myapp01
  labels:
    app: myapp01
spec:
  ## Pod级别
  volumes:
  - name: myconfig
    configMap:
      name: many-key-value-01
      # <== 非强制的意义
      #   默认值为false
      #      强制
      #      此资源对象在创建时,不忽略所引用cm资源对象是否存在
      #      建议强制
      #   设置值为true
      #      非强制，忽略所引用cm资源对象是否存在
      #      不建议非强制 
      optional: false

  ## 容器级别之主容器
  containers: 
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    volumeMounts:
    - name: myconfig
      mountPath: /data
      readOnly: false
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
