apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: myapp01
  labels:
    app: myapp01
spec:
  ## Pod级别
  volumes:
  - name: myconfig
    configMap:
      name: many-key-value-01

  ## 容器级别之主容器
  containers: 
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    volumeMounts:
    - name: myconfig
      mountPath: /data
      readOnly: false
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
