apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wyc
  name: app02
  labels:
    deploy: app02
spec:
  # <== 单副本,rbd只支持单路
  replicas: 1
  selector:
    matchLabels:
      app: app02
  template:
    metadata:
      labels:
        app: app02
        project: wyc
        env: prod
    spec:
      # Pod级别
      volumes:
        - name: data
          rbd:
            # 其存储系统之Ceph之monitors组件的连接地址和相应volume（subvolume）的路径
            monitors:                                                            # 根据存储管理员所提供的信息
              - "172.31.7.211:6789"
              - "172.31.7.212:6789"
              - "172.31.7.213:6789"
            pool: rbd-wyc-project-data                                           # 根据存储管理员所提供的信息
            image: app02-data                                                    # 根据存储管理员所提供的信息

            # 认证时的用户和相应的secret(以secrets交付到当前所在名称空间了),各woker node上不需要用户的keyring文件
            user: "wycrbd"                                                       # 根据存储管理员所提供的信息
            keyring: ""                                                          # 它默认是/etc/ceph/keyring,我不用它,相应worker node上也没有,我指定为空
            secretRef:
              name: wyc-project-ceph-rbd-in-wycrbd-user-key                      # 其metadata.namespace所指名称空间中得存在相应secrets资源对象

            # 在格式化时,格式化成什么文件系统
            fsType: ext4

            # 在Pod级别加载volume后,在这一层面,指定是否只读,为false表示可读写
            readOnly: false

      # 容器级别之主容器
      containers:
        - name: app02
          image: docker.io/library/busybox:latest
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: false
          command: 
            - "/bin/sh"
          args:
            - "-c"
            - "sleep 10000000"
