apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: myapp01
spec:
  # Pod级别
  imagePullSecrets: 
  - name: "myhuaweicloud.com.image.read"

  # 容器级别之主容器
  containers:
  - name: myapp01
    # 此镜像是私有的,pull时需要认证，得用到pods.spec.imagePullSecrets中所指定的secrets资源对象
    image: swr.cn-north-1.myhuaweicloud.com/qepyd/nginx:1.16
    imagePullPolicy: Always
