---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: binbin
  name: app22
  labels:
    deploy: app22
spec:
  # Pod副本数
  replicas: 2
  selector:
    matchLabels:
      project: binbin
      env: prod
      app: app22
  template:
    metadata:
      labels:
        project: binbin
        env: prod
        app: app22
    spec:
      # Pod级别
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: "app22"
          readOnly: false

      # 容器级别之主容器
      containers:
      - name: app22
        image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
        imagePullPolicy: Always
        volumeMounts:
        - name: data-volume
          mountPath: /data/
          readOnly: false
        command:
        - "/bin/sh"
        args: 
        - "-c"
        - "sleep 10000000000"
      - name: sidecar
        image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
        imagePullPolicy: Always
        volumeMounts:
        - name: data-volume
          mountPath: /data/
          readOnly: false
        command:
        - "/bin/sh"
        args:
        - "-c"
        - "sleep 10000000000"
---

