apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: <string>
  name: <string>
  labels: <map[string]string>
  annotations: <map[string]string>
spec:
  hard: <map[string]string>
  scopeSelector: <Object>
  scopes: <[]string>
