apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: only-requests-but-requests-effect-pod-dispatch-02 
  labels:
    app: only-requests-but-requests-effect-pod-dispatch-02
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源（只有requests(拥有requests,没有limits)）
    #     Pod的调度
    #        会将 resources.requests 中的相关资源需求算在内。
    #     容器资源限制
    #        没有限制,困为没有 resources.limits 字段。  
    resources:
      requests:
        cpu: "100m"
        memory: "100Gi"

# 上述有1个容器(主容器)
#    Pod在调度时会将满足以下能力的worker node先选择出来,再择优选择。
#      cpu: 100m
#      memory: 100Gi
#
#    Pod中的容器对资源的使用限制
#      没有限制,因为没有pods.spec.containers.resources.limits字段
#

