---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: basic-requests-not-greater-limtis-ok 
  labels:
    app: basic-requests-not-greater-limtis-ok 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    resources:
      limits:
        cpu: "100m"
        memory: "512Mi"
      requests:
        cpu: "50m"
        memory: "256Mi"
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
    resources:
      limits:
        cpu: "100m"
        memory: "512Mi"
      requests:
        cpu: "50m"       
        memory: "256Mi"    
---
#
# 此资源对象所在namespace的describe信息为
#   root@master01:~# kubectl describe ns lili
#   Name:         lili
#   Labels:       kubernetes.io/metadata.name=lili
#   Annotations:  <none>
#   Status:       Active
#   
#   No resource quota.
#  
#   No LimitRange resource.
#
# 此资源对象可以被kube-apiserver所接受，创建。
#   此资源对象(Pod)中各容器的limits和requests在线信息可用以下信息获得
#     kubectl get -f 02.pods_basic-requests-not-greater-limtis-ok.yaml  -o json | jq ".spec.containers[].name, .spec.containers[].resources"
#   在我的kubernetes环境是可以被调度，有worker node满足Pod的总requests
#
