apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: only-requests-effect-pod-dispatch-04 
  labels:
    app: only-requests-effect-pod-dispatch-04
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源限制
    #     只有requests(拥有requests,没有limits),会影响Pod的调度:
    #        调度时需要有worker node能够满足所需cpu、memory的能力。
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
       
