---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: basic-limitsnotexist-not-generate-based-on-requests 
  labels:
    app: basic-limitsnotexist-not-generate-based-on-requests 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源限制(limits)和请求(requests)
    #     没有limits，有requests
    #     limits不会根据requests的定义生成(在没有外力的干扰下)
    resources:
      requests:
        cpu: "50m"
        memory: "216Mi"
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
    # <== 资源限制(limits)和请求(requests)
    #     没有limits，有requests
    #     limits不会根据requests的定义生成(在没有外力的干扰下)
    resources:
      requests:
        cpu: "50m"
        memory: "216Mi"
---
#
# 此资源对象所在namespace的describe信息为
#   root@master01:~# kubectl describe ns lili
#   Name:         lili
#   Labels:       kubernetes.io/metadata.name=lili
#   Annotations:  <none>
#   Status:       Active
#   
#   No resource quota.
#  
#   No LimitRange resource.
#
# 此资源对象可以被kube-apiserver所接受，创建。
#   此资源对象(Pod)中各容器的limits和requests在线信息可用以下信息获得
#       kubectl get -f 04.pods_basic-limitsnotexist-not-generate-based-on-requests.yaml  -o json | jq ".spec.containers[].name, .spec.containers[].resources"
#   在我的kubernetes环境是可以被调度，有worker node满足Pod的总requests
#

