apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: resources-requests 
  labels:
    app: resources-requests 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源限制(limits)和请求(requests)
    #     没有resources的limits，但有requests。
    #     不会根据requests中的key:value为limits进行配置。
    #     注意：可能会根据其它资源对象(例如LimitRange)的设置为limits进行配置
    resources:
      requests:
        cpu: "50m"
        memory: "216Mi"
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
    # <== 资源限制(limits)和请求(requests)
    #     没有resources的limits，但有requests。
    #     不会根据requests中的key:value为limits进行配置。
    #     注意：可能会根据其它资源对象(例如LimitRange)的设置为limits进行配置
    resources:
      requests:
        cpu: "50m"
        memory: "216Mi"
