---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: app-exceed-requests-but-not-execeed-limits-memory 
  labels:
    app: app-exceed-requests-but-not-execeed-limits-memory 
spec:
  containers:
  - name: stress-ng
    image: swr.cn-north-1.myhuaweicloud.com/qepyd/stress:1.0.4 
    # <== 启动命令
    #     共分配了1个进程，每个进程占用60M内存
    #     未超过resources.limits.memory
    #     已超过resources.limits.requests
    command:
    - "stress"
    args:
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "60M"
    - "--vm-hang"
    - "1"
    # <== 资源的请求(requests)和限制(limits)
    resources:
      limits:
        memory: "100Mi" 
      requests:
        memory: "50Mi"
---
#
# 
