apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: only-limits-effect-pod-dispatch-05
  labels:
    app: only-limits-effect-pod-dispatch-05
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源（只有limits(没有requests,拥有limits)）
    #     Pod的调度
    #        会将 resources.requests 中的相关资源需求算在内
    #        这里没有定义 resources.requests 字段
    #          会根据 resources.limits 中的定义 进行填充。
    #          可从在线 manifests 中看到
    #     容器资源限制
    #        根据 resources.limits 中的定义
    resources:
      limits:
        cpu: "100m"
        memory: "100Mi"
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
    # <== 资源（只有limits(没有requests,拥有limits)）
    #     Pod的调度
    #        会将 resources.requests 中的相关资源需求算在内
    #        这里没有定义 resources.requests 字段
    #          会根据 resources.limits 中的定义 进行填充。
    #          可从在线 manifests 中看到
    #     容器资源限制
    #        根据 resources.limits 中的定义
    resources:
      limits:
        cpu: "50m"
        memory: "50Mi" 

# 上述有2个容器(主容器)
#    Pod在调度时会将满足以下能力的worker node先选择出来,再择优选择。
#      cpu: 100m + 50m = 150m
#      memory: 100Mi + 50Mi = 150Mi
#
#    Pod中的容器对资源的使用限制
#      myapp01容器最多只能使用cpu 100m, memory 100Mi
#      busybox容器最多只能使用cpu 50m, memory 50Mi
# 
