---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: app-exceed-limits-cpu 
  labels:
    app: app-exceed-limits-cpu 
spec:
  containers:
  - name: vish-stress
    image: swr.cn-north-1.myhuaweicloud.com/qepyd/vish-stress:latest 
    args:
    - -cpus
    - "1"
    resources:
      limits:
        cpu: "0.5"
---
#
# 主容器vish-stress会占用1核的cpu，超过了limits的0.5。
#  会限制cpu的使用率不超过0.5
#  
