---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: pod-qos-to-guaranteed 
  labels:
    app: pod-qos-to-guaranteed 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    resources:
      limits:
        cpu: "100m"
        memory: "100Mi"
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
    resources:
      limits:
        cpu: "50m"
        memory: "50Mi" 
---
#
#  Pod的服务质量(Qos)之Guaranteed(保证)
# 
#  Guaranteed > Bustable > BestEffort
# 
#  https://kubernetes.io/zh-cn/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed
#
#  Pod中所有主容器均得配置cpu、memory的limits和requests，
#  且requests中资源量得等于limits中的资源量
#
