apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: pod-qos-to-burstable 
  labels:
    app: pod-qos-to-burstable
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    resources:
      limits:
        memory: "100Mi"
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"


## Pod的服务质量(Qos)之Bustable(满足)
#
#  Guaranteed > Bustable > BestEffort
# 
#  官方：https://kubernetes.io/zh-cn/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-burstable
#   
#  Pod中至少得有一个容器具备cpu或memory的requests或limits。 
#
