apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: not-container-memory-limit
  labels:
    app: not-container-memory-limit
spec:
  containers:
  - name: stress
    image: swr.cn-north-1.myhuaweicloud.com/qepyd/stress:1.0.4
    # <== 启动命令
    #     尝试分配超出其限制的内存
    command:
    - "stress"
    args:
    - "--vm"
    - "1"
    - "--vm-bytes"
    - "40M"
    - "--vm-hang"
    - "1"
    # <== 资源的请求(requests)和限制(limits)
    resources:
      limits:
        memory: "50Mi" 

## 容器限制(limits)memory为50Mi
#  01:容器中的应用程序会占用40M的内存，不会超过memory limits。
#  02:该容器不会成为被终止的候选容器。
#
