
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: containers-max-min-cpu-mem-not-ratio-2  
spec:
  limits:
  - default:
      cpu: "200m"        # 最少min,最大max
      memory: "256Mi"    # 最少min,最大max
    defaultRequest:
      cpu: "200m"        # 最少min,最大max
      memory: "256Mi"    # 最少min,最大max
    max:
      cpu: "400m"
      memory: "512Mi"
    min:
      cpu: "200m"
      memory: "256Mi"
    type: Container
---

