apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: all-container-not-cpu-requests-limits 
  labels:
    app: all-container-not-cpu-requests-limits 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
