---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: lili
  name: myapp01
  labels:
    deploy: myapp01
spec:
  # 匹配选择器匹配template中Pod的标签
  selector:
    matchLabels:
      app: myapp01

  # 模板中对Pod进行期望状态定义,
  # 就看你对pods资源的API规划有多熟练了。
  template:
    metadata:
      # 这里就不用指明namespace和name了
      labels:
        app: myapp01
    spec:
      #nodeName: node01
      #nodeSelector:
      #  project: wyc

      tolerations:
        - key: ""
          operator: "Exists"
          effect: NoSchedule

      containers:
        - name: myapp01
          image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
          ports:
            - name: http-80
              containerPort: 80
