---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: default
  name: client 
spec:
  selector:
    matchLabels:
      app: client 
  template:
    metadata:
      labels:
        app: client 
    spec:
      containers:
      - name: admin-toolbox
        image: swr.cn-north-1.myhuaweicloud.com/chenliang/admin-toolbox:v1.0
        imagePullPolicy: IfNotPresent
        args:
        - "ping -c 2  223.5.5.5  &&  sleep 1000000000"
