---
# 基本说明:
#   用于在相应的woker node上运行Pod(不共享宿主机网络名称空间)
#   Pod中的某容器先访问互联网IPv4(例如:223.5.5.5),若成功后sleep 10000
#   若不能成功访问互联网IPv4,那么容器是无法前台运行,Pod也不会处于Running状态。
# 使用场景：
#   例如：安装好k8s的cni插件后
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: default
  name: pod-in-container-test-visit-internet-ipv4
spec:
  selector:
    matchLabels:
      app: pod-in-container-test-visit-internet-ipv4
  template:
    metadata:
      labels:
        app: pod-in-container-test-visit-internet-ipv4
    spec:
      containers:
      - name: admin-toolbox
        image: swr.cn-north-1.myhuaweicloud.com/chenliang/admin-toolbox:v1.0
        imagePullPolicy: IfNotPresent
        args:
        - "ping -c 2  223.5.5.5  &&  sleep 10000"
