apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: initc-containers
  labels:
    app: initc-containers
spec:
  initContainers:
  - name: echo
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    imagePullPolicy: Always
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "echo 'init containers'"
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    imagePullPolicy: Always
