---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: defined-requests 
  labels:
    app: defined-requests 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源请求和限制
    #     有resources.requests
    #     没有resources.limits
    #     resources.limits中key:value对不会根据resources.requests字段下的key:value来生成
    resources:
      ### 没有limits字段
      # 根据LimitRnage资源spec.limits.default.memory最大的LimitRange资源对象为其进行设置

      ### 有requests字段
      requests:
        cpu: "50m"     
        memory: "50Mi"

      # 注意：
      # requests中相应资源的值不能大于limits中相应资源的值,这是最基本的。
---
