apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: workingdir 
  labels:
    app: workingdir
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    imagePullPolicy: Always
    workingDir: "/data/lili/"
