apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: all-container-not-memory-requests-limits 
  labels:
    app: all-container-not-memory-requests-limits 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
  - name: busybox
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"

## 此资源对象所在namespace中存在的一个limitrange资源对象
#  limitrange/mem-limit-range
#    defaultrequests: 
#        memory: 256Mi
#    default:
#        memory: 512Mi
#
## 此资源对象中各容器没有定义任何的resources，各容器的资源限制如下所示
#  myapp01
#    resources:
#      requests:
#        memory: 256Mi
#      limits:
#        memory: 512Mi
#
#  busybox
#    resources:
#      requests:
#        memory: 256Mi
#      limits:
#        memory: 512Mi
#
#
