apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: memory-comprehensive 
  labels:
    app: memory-comprehensive 
spec:
  containers:
  - name: busybox01
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"

  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    resources:
      limits:
        memory: "600Mi"

  - name: youapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/busybox:1.31
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "sleep 1000000000"
    resources:
      requests:
        memory: "512Mi"
