apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: mem-limit-range
spec:
  limits:
    - type: Container
      # 支持在线更改
      defaultRequest:
        memory: 256Mi
      # 支持在线更改
      default:
        memory: 512Mi

#### 说明
# 对所在名称空间(lili)中各Pod资源对象中的容器(Container)进行memory的limits。
#   01：若所在名称空间(lili)中的Pod里面容器没有进行memory的requests、limits。
#       则根据LimitRange资源对象所定义的进行设置。
#
#   02：若所在名称空间(lili)中的Pod里面容器有进行memory的requests和limits设置,
#       例如1：resources.limits.memory: 600Mi   # <== 其resources.requests下会填充memory: 600Mi
#       例如2：resources.requests.memory: 800Mi  resources.limits.memory: 800Mi 
#       则不受LimitRange资源对象所定义的限制，即使超过了。
#
#   03：若所在名称空间(lili)中的Pod里面容器只有requests字段进行memory的设置。
#       不能大于LimitRange的limits.default.memory的值(512Mi)
