
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: default-cpu-mem 
spec:
  limits:
    # <== 各Pod中其各container之resources.limits默认资源量
    #     可在线更改
  - default: 
      cpu: "600m" 
      memory: "768Mi"
    # <== 各Pod中其各container之resources.requests默认资源量
    #     可在线更改
    #     相关资源量不能大于 default 中的。
    defaultRequest:  
      cpu: "200m"
      memory: "256Mi"
    # <== 此资源对象所在namespace下各Pod中其各container
    type: Container
---
#
# 此资源对象创建后，其在线manifests的关键信息如下所示
#  spec:
#    limits:
#    - default:
#        cpu: 600m
#        memory: 656Mi
#      defaultRequest:
#        cpu: 200m
#        memory: 256Mi
#      type: Container
#
# 此资源对象所在namespace其describe的关键信息如下所示
#   No resource quota.
#   
#   Resource Limits
#    Type       Resource  Min  Max  Default Request  Default Limit  Max Limit/Request Ratio
#    ----       --------  ---  ---  ---------------  -------------  -----------------------
#    Container  cpu       -    -    200m             600m           -
#    Container  memory    -    -    256Mi            768Mi          -
#
