---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: default-cpu-mem 
spec:
  limits:
    # <== 各Pod其container的resources.limits默认配置
    #     可在线更改
  - default:
      cpu: "500m" 
      memory: "612Mi"
    # <== 各Pod其container的resources.requests默认配置
    #     可在线更改
    defaultRequest:
      cpu: "300m"
      memory: "356Mi"
    # <== 此资源对象所在namespace下各Pod中的container
    type: Container
---
