---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: defined-requests-limits-02 
  labels:
    app: defined-requests-limits-02 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源请求和限制
    #     没有resources.requests
    #     有resources.limits
    #     resources.requests字段中的key:value对会根据resources.limits字段下的key:value对来生成。
    resources:
      limits:
        cpu: "900m"
        memory: "700Mi"
---
#
# 此资源对象所在namespace其describe的关键信息如下所示
#   No resource quota.
#   
#   Resource Limits
#    Type       Resource  Min  Max  Default Request  Default Limit  Max Limit/Request Ratio
#    ----       --------  ---  ---  ---------------  -------------  -----------------------
#    Container  cpu       -    -    300m             500m           -
#    Container  memory    -    -    356Mi            612Mi          -
#
# 此资源对象中 各主容器 有人为定义resoruces，其计算资源的值可以随便定义，不受LimitRange的限制。
#   主容器myapp01
#     resources:
#       limits:
#         cpu: 900m
#         memory: 700Mi
#       requests:
#         cpu: 900m
#         memory: 700Mi
#

