
---
apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: defined-requests 
  labels:
    app: defined-requests 
spec:
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    # <== 资源请求和限制
    #     有resources.requests
    #     没有resources.limits
    #     resources.limits中key:value对不会根据resources.requests字段下的key:value来生成
    resources:
      #没有limits字段
      #会根据LimitRange中的spce.limits.default字段生成

      ### 有requests字段
      requests:   # requests中相应计算资源的值不能大于limits中相应计算资源的值,这是最基本的哈
        cpu: "50m"     
        memory: "50Mi"
---
#
# 此资源对象所在namespace其describe的关键信息如下所示
#   No resource quota.
#   
#   Resource Limits
#    Type       Resource  Min  Max  Default Request  Default Limit  Max Limit/Request Ratio
#    ----       --------  ---  ---  ---------------  -------------  -----------------------
#    Container  cpu       -    -    300m             500m           -
#    Container  memory    -    -    356Mi            612Mi          -
#
# 此资源对象中 各主容器 有人为定义resoruces，其计算资源的值可以随便定义，不受LimitRange的限制。
#   主容器myapp01
#     resources:
#       limits:
#         cpu: 500m
#         memory: 612Mi
#       requests:
#         cpu: 50m
#         memory: 50Mi
#

