---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: lili
  name: containers-max-min-cpu-mem-not-have-ratio-1 
spec:
  limits:
  - type: Container
    max:
      cpu: "400m"
      memory: "512Mi"
    min:
      cpu: "200m"
      memory: "256Mi"
---
#
# 此资源对象创建后，其在线manifests的关键信息如下所示
#   spec:
#     limits:
#     - default:            # 创建LimitRange资源对象时,未指定,根据max的生成
#         cpu: 400m
#         memory: 512Mi
#       defaultRequest:     # 创建LimitRange资源对象时,未指定,根据min的生成
#         cpu: 400m
#         memory: 512Mi
#       max:
#         cpu: 400m
#         memory: 512Mi
#       min:
#         cpu: 200m
#         memory: 256Mi
#       type: Container
#
# 此资源对象创建后，其所在namespace的describe关键信息如下所示
#   No resource quota.
#   
#   Resource Limits
#     Type       Resource  Min    Max    Default Request  Default Limit  Max Limit/Request Ratio
#     ----       --------  ---    ---    ---------------  -------------  -----------------------
#     Container  cpu       200m   400m   400m             400m           -
#     Container  memory    256Mi  512Mi  512Mi            512Mi          -
#
