apiVersion: v1
kind: Service
metadata:
  namespace: lili
  name: baidu
spec:
  selector:
    app: myapp
  type: ExternalName
  externalName: www.magedu.com
  externalIPs:
    - 1.1.1.1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

