apiVersion: v1
kind: Pod
metadata:
  namespace: lili
  name: expose
  labels:
    app: expose 
spec:
  ## 容器级别之主容器
  containers:
  - name: myapp01
    image: swr.cn-north-1.myhuaweicloud.com/library/nginx:1.16
    imagePullPolicy: Always
    # <== 从容器要公开的端口
    #     暴露
    #       其hostPort的端口会存在于此Pod所在worker node的iptables中
    #       即在此Pod所在worker node中用ss -lntup是看不到hostPort所指定的端口的。
    #       注意：不要使用这种暴露方式
    ports:
    - name: http-80
      containerPort: 80
      hostPort: 8080
