apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lili 
  name: app02
  labels:
    deploy: app02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app02
  template:
    metadata:
      labels:
        app: app02
        project: wyc
        env: prod
    spec:
      # Pod级别
      volumes:
        - name: logs
          cephfs:
            # 其存储系统之Ceph之monitors组件的连接地址和相应volume（subvolume）的路径
            monitors:                                                          # 根据存储管理员所提供的信息
              - "172.31.7.211:6789"
              - "172.31.7.212:6789"
              - "172.31.7.213:6789"
            path:  "/volumes/app02/logs/417909da-b727-495b-96f2-06da2cca686f"  # 根据存储管理员所提供的信息

            # 认证的用户和secret(不是keyring哈)
            # user: "client.wycfs"
            user: "wycfs"                                          # 根据存储管理员所提供的信息
            secretRef: 
              name: "wyc-project-cephfs-in-wycfs-user-key"         # 得事先得在metadata.namespace所指定名称空间中存在

            # 在Pod级别加载volume后,在这一层面,允许其读写
            readOnly: false

      # 容器级别之主容器
      containers:
        - name: app02
          image: docker.io/library/nginx:latest
          volumeMounts:
            - name: logs
              mountPath: /var/log/nginx/
              readOnly: false
 
