---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: binbin
  name: app31
  labels:
    project: binbin
    env: prod
    app: app31
spec:
  # 准备集群级别pv的顺序为
  # volumeMode--->labels--->storageClassName--->accessModes-->capacity
  
  volumeMode: Filesystem

  selector:
    matchLabels:
      project: binbin
      env: prod
      app: app31
 
  storageClassName: "binbin-project-prod-static-pv"
  
  accessModes: 
  - ReadWriteMany
  
  resources: 
    limits:
      storage: 10Gi 
    requests:
      storage: 10Gi 
---

